

def test(model,test_data_path):
    ''' Test a certain model based on fixed classification metrics ...'''
    # TODO
    # auc = ...
    # f1 = ...
    # accuracy = ...
    # recall = ...
    # save plot of roc to results/figures/
    return None
